### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by sayanmondal2098** [sayanmondal2098/traffic#3]
Create a highly responsive webpage for Login and Signup using email and password

**Comment by aritraroy24** [comment]
@sayanmondal2098 can I use firebase for the login functionality??? If yes, then I'll like to work on this topic...

**Comment by manikaaggarwal** [comment]
@sayanmondal2098 Do you want just the pages to be designed? I can do it.

**Comment by agatharejina** [comment]
Hi! I'd to contribute on this project.
- Are there any addition for general information in Signup page like full name, phone number  etc?
- Do you want the Login and the Signup page to work ? or only the UI Design?
- Can I use React Hooks?

**Comment by sayanmondal2098** [comment]
Yes , I just want to design the Login Pages
No need to add any kind of backend functionality.
thank you for your time 
@manikaaggarwal @agatharejina @aritraroy24

**Comment by aritraroy24** [comment]
@sayanmondal2098 assign it please...

**Comment by sayanmondal2098** [comment]
@manikaaggarwal @agatharejina @aritraroy24 The Signup should accept Name, password, city, email, phone, and coordinates (to be detected). All of these fields are mandatory.
On sign-in page,  only email/phone and password are sufficient. No Gmail/Facebook login is required. 
We need to convey the state to the next steps for further processing. (Dashboard part) .
@aritraroy24  It's open for all .

**Comment by agatharejina** [comment]
Can you elaborate on the coordinates input? It's just that, if you wanted to know the dynamic position of the user, then you might want to get the coordinates whenever the user opens the application.

**Comment by sayanmondal2098** [comment]
@agatharejina  we already get few pr about it. The sign up page it already created. You just have to get their coordinates automatically . For this I create other issue. Please look into this. Thanks .
